### ISSUE TITLE
Does this support format of text? 

### ISSUE THREAD

**Issue by programus** [BUPTlhuanyu/word-to-html#1]
[Chinese]
看到源代码里的注释是中文，我先用中文来写以提高沟通效率。

我现在面临一个将Word文件内容展现在网页里的任务，发现了你这个库。想咨询一下，这个库是否支持把Word里的文字格式（字体、大小、颜色……）也一同转化入HTML？

简单看了一下源代码，好像对表格有很好的支持和处理，但对文本，只是把 `<w:r><w:t>` 里的内容抽取出来，中间的格式（通常包含在 `<w:rPr>` 之类里的内容并没有抽取。

不知道是我看漏了，还是目前暂时还不支持？

[English]

To make others also understand the question, I simply summarize my question in English also. 

I notice this library supports tables in Word file well, but didn't find the part to support the format or style of text, usually defined in `<w:rPr>` tag in Office Open XML. 

Does this library really not support styles of text currently?

**Comment by BUPTlhuanyu** [comment]
是可以支持的，欢迎重构 + pr

**Comment by programus** [comment]
请问，有可以动的例子可以参考一下吗？
比如我从网页上选择一个Word文件，然后在下面显示出HTML的渲染结果。

或者，指导我一下怎么做也行，我现在没太搞明白这个东西是应该在服务器端使用还是可以直接客户端使用…… 😅

**Comment by BUPTlhuanyu** [comment]
> 请问，有可以动的例子可以参考一下吗？ 比如我从网页上选择一个Word文件，然后在下面显示出HTML的渲染结果。
> 
> 或者，指导我一下怎么做也行，我现在没太搞明白这个东西是应该在服务器端使用还是可以直接客户端使用…… 😅

这个用到了 adm-zip，用到了 node 的 api，没办法直接在浏览器中使用。

**Comment by programus** [comment]
明白了，看来我只能再做一个新的了……
谢谢！

**Comment by BUPTlhuanyu** [comment]
@programus 
看了下代码，是 ok 的，处理了 w:rFonts，这个节点包含了文字的相关信息

**Comment by BUPTlhuanyu** [comment]
@programus 
重构了一版，图片对不上的问题也解决了

**Comment by programus** [comment]
@BUPTlhuanyu 谢谢！我已经在着手做一个新的了。
因为我们还需要对转换成HTML的文字进行高亮并回写到docx里，而且要求在浏览器里使用，所以恐怕不能直接用你这个了。

不过，或许我会来偷些代码逻辑过去。 😁 

我做的这个在这里，还有很多格式没有处理，而且已经有了不少严重的bug了。但是已经支持在浏览器端解压缩docx并取出其中的xml了。或许这部分你可以参考一下。

https://github.com/programus/word-docx
